project:
  type: book

book:
  title: "A Solid Start to ggplot2"
  author: "Joyce Robbins"
  date: "5/26/2023"
  site-url: https://jtr13.github.io/graphs
  repo-url: https://github.com/jtr13/graphs
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - grammar.qmd
    - layers.qmd
    - code.qmd
    - acknowledgments.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [default, style/graphs.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true
  fig-height: 4
  fig-width: 4

editor: source

